[package]
name = "handoff-register"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdt-sample = "0.2.0"
rand = "0.8.5"
color-print = "0.3.4"
serde = "1.0.160"
indicatif = "0.17.3"