[package]
name = "thesis-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdt-sample = "0.1.0"
rand = "0.8.5"
color-print = "0.3.4"